// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkkl8E3HIdejVr0zp_v_2ij3jG6wBrvtE',
    appId: '1:229146400439:web:8fa17087f6c68972d89f32',
    messagingSenderId: '229146400439',
    projectId: 'final-ppb',
    authDomain: 'final-ppb.firebaseapp.com',
    storageBucket: 'final-ppb.firebasestorage.app',
    measurementId: 'G-HHDT4PV6QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeOzjT29JsvqyPtOM4Uu1iK-rTm4XmLeE',
    appId: '1:229146400439:android:a4571b48a56d474cd89f32',
    messagingSenderId: '229146400439',
    projectId: 'final-ppb',
    storageBucket: 'final-ppb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKLjQHv6NKuE2AkSSMqsYSPqFOuJFgY_U',
    appId: '1:229146400439:ios:65936d5a24abac55d89f32',
    messagingSenderId: '229146400439',
    projectId: 'final-ppb',
    storageBucket: 'final-ppb.firebasestorage.app',
    iosBundleId: 'com.example.finalPpb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKLjQHv6NKuE2AkSSMqsYSPqFOuJFgY_U',
    appId: '1:229146400439:ios:65936d5a24abac55d89f32',
    messagingSenderId: '229146400439',
    projectId: 'final-ppb',
    storageBucket: 'final-ppb.firebasestorage.app',
    iosBundleId: 'com.example.finalPpb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkkl8E3HIdejVr0zp_v_2ij3jG6wBrvtE',
    appId: '1:229146400439:web:783d53abc6faf86bd89f32',
    messagingSenderId: '229146400439',
    projectId: 'final-ppb',
    authDomain: 'final-ppb.firebaseapp.com',
    storageBucket: 'final-ppb.firebasestorage.app',
    measurementId: 'G-ZSX5CPH9RK',
  );
}
